name: Test Basic GitHub Context

on:
  push:
    branches:
      - main

jobs:
  print_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Branch Reference: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
