name: Test Push Event

on: 
  push:
    branches:
      - main

jobs:
  check_run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Event Details
        run: echo "Push event was triggered on branch:"
