name: Super-Linter Workflow

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  checks: write  
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true     # Enable Python validation
          VALIDATE_JS: false        # Disable JavaScript validation
          VALIDATE_HTML: false      # Disable HTML validation
          VALIDATE_YAML: false      # Disable YAML validation
