name: Simulate Check Workflow

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run some tests
        run: |
          echo "Running tests..."
          sleep 5
          echo "Tests completed!"
